<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="4" passed="3" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-05-08T00:52:42 EDT" name="Default suite" finished-at="2023-05-08T00:52:46 EDT" duration-ms="3299">
    <groups>
    </groups>
    <test started-at="2023-05-08T00:52:42 EDT" name="Default test" finished-at="2023-05-08T00:52:46 EDT" duration-ms="3299">
      <class name="pages.APILoginPage">
        <test-method is-config="true" signature="setup()[pri:0, instance:pages.APILoginPage@47987356]" started-at="2023-05-08T00:52:42 EDT" name="setup" finished-at="2023-05-08T00:52:43 EDT" duration-ms="618" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="testcase1ValidLogin()[pri:0, instance:pages.APILoginPage@47987356]" started-at="2023-05-08T00:52:43 EDT" name="testcase1ValidLogin" finished-at="2023-05-08T00:52:45 EDT" duration-ms="1942" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testcase1ValidLogin -->
        <test-method signature="testcase2IncorrectEndpoint()[pri:0, instance:pages.APILoginPage@47987356]" started-at="2023-05-08T00:52:45 EDT" name="testcase2IncorrectEndpoint" finished-at="2023-05-08T00:52:45 EDT" duration-ms="237" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testcase2IncorrectEndpoint -->
        <test-method signature="testcase3ImproperBody()[pri:0, instance:pages.APILoginPage@47987356]" started-at="2023-05-08T00:52:45 EDT" name="testcase3ImproperBody" finished-at="2023-05-08T00:52:45 EDT" duration-ms="231" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testcase3ImproperBody -->
        <test-method signature="testcase4WrongUsernamePassword()[pri:0, instance:pages.APILoginPage@47987356]" started-at="2023-05-08T00:52:45 EDT" name="testcase4WrongUsernamePassword" finished-at="2023-05-08T00:52:46 EDT" duration-ms="239" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [405] but found [422]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [405] but found [422]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:907)
at org.testng.Assert.assertEquals(Assert.java:917)
at pages.APILoginPage.testcase4WrongUsernamePassword(APILoginPage.java:129)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testcase4WrongUsernamePassword -->
      </class> <!-- pages.APILoginPage -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
